### ISSUE TITLE
Interpolation feature

### ISSUE THREAD

**Issue by sergiomallasen** [darkpgmr/DarkLabel#11]
What does the interpolation feature do? How does it work? Could you make a small tutorial on how to use it? I'm getting tired of smashing the Next &Predict button
Thanks!!

**Comment by darkpgmr** [comment]
1. start interpolation by pressing 'begin interpolation' button
2. draw box on the object you want to label
3. jump to another frame (skip a number of frames)
4. draw box on the same object on the jumped frame
5. jump to another frame and label the object (repeat this process)
6. if you done, navigate the frames to check if the interpolated boxes (black colored boxes) is well-positioned.
7. if the interpolation is not good (misplaced) on some frame, draw box again on that frames
8. if you done, finalize the interpolation by pressing 'end interpolation' button

Another tip..
you don't need to click 'Next & Predict' button. It can be done by pressing 'Enter' or 'Spacebar' key.
(you can change the key mapping in the darklabel.yml)
