### ISSUE TITLE
Small target labeling 

### ISSUE THREAD

**Issue by primaryer** [darkpgmr/DarkLabel#3]
The tracking and labeling functions of the software are very useful, but when I want to label a small target of 10x10 pixels, I find I can't do that.

**Comment by darkpgmr** [comment]
I intentionally blocked to label too small objects to prevent drawing boxes by mistake. However, I will parameterize it in next update.

**Comment by darkpgmr** [comment]
The minimum object size is now adjustable as a parameter. 579232bef34a742400a9c3eb28ac22e329745312
please check [darklabel2.3-update2](https://github.com/darkpgmr/DarkLabel/releases/tag/darklabel2.3-update2)
