### ISSUE TITLE
MOT annotation format

### ISSUE THREAD

**Issue by severous** [darkpgmr/DarkLabel#5]
@darkpgmr How to convert to MOT's annotation format for multi-target tracking

**Comment by darkpgmr** [comment]
DarkLabel dose not support MOT's format.
However, you can define your own format in darklabel.yml like that:
<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z>
'''
format_mot: 
  data_fmt: [fn, id, x1, y1, w, h]
  gt_file_ext: "txt"
  gt_merged: 1
'''
And then, you can append "conf,-1,-1,-1" for each line after finishing your annotation.

Another way in case any noisy value for <conf>, <x>, <y>, <z> are ok:
'''
format_mot: 
  data_fmt: [fn, id, x1, y1, w, h, difficult, difficult, difficult, difficult]
  gt_file_ext: "txt"
  gt_merged: 1
'''

**Comment by darkpgmr** [comment]
Now it support MOT format

**Comment by QiyuLuo** [comment]
@darkpgmr Thank your for your Open source tools. Since the MOT dataset is given in the form of pictures, when annotating  it will appear **save failed: format specifier 'fn' cannot be applied for images!** How can I solve this problem？

**Comment by Breezewrf** [comment]
> @darkpgmr Thank your for your Open source tools. Since the MOT dataset is given in the form of pictures, when annotating it will appear **save failed: format specifier 'fn' cannot be applied for images!** How can I solve this problem？

hello I got the same problem, have you solved it?

**Comment by Breezewrf** [comment]
> > @darkpgmr Thank your for your Open source tools. Since the MOT dataset is given in the form of pictures, when annotating it will appear **save failed: format specifier 'fn' cannot be applied for images!** How can I solve this problem？
> 
> hello I got the same problem, have you solved it?

got it   it has to be video...
