### ISSUE TITLE
Change File name

### ISSUE THREAD

**Issue by Syizuril** [darkpgmr/DarkLabel#6]
Is there a way to change the file format from video for example using the filename and frame like "image1_00000001.xml" and at the same time save the image with the same name ?

**Comment by blessedDS** [comment]
How to save the images and xml with the same name as of videos

**Comment by roricljy** [comment]
Currently the program doesn't support such naming. One possible solution would be to create a folder with the same name as the video name, and then save the images and xml below the folder. Please understand that I can't support everyone's need. I want to keep the program as general but minimal as possible.
