### ISSUE TITLE
Can't create data_fmt like [x1, y1, w, h]

### ISSUE THREAD

**Issue by pilot00** [darkpgmr/DarkLabel#7]
Hello, 
Why cannot I create a format like this:
format8: 
  data_fmt: [x1, y1, w, h]
  gt_file_ext: "txt"
  gt_merged: 1

When I try to save the GT file, it warns that "Save failed: format specifier 'iname' is missing".
So is iname necessary?
Could you please give me some solutions?

Many thanks!

**Comment by darkpgmr** [comment]
'iname' is required as an identifier in case 'gt_merged' is set to be 1 in order to match labeled data to the source image.
You can omit iname if you save the labels in separate files for each image (gt_merged: 0).
You can close this issue if your problem is solved.

**Comment by xyl-507** [comment]
@darkpgmr @pilot00 
When 'gt_merged' is set to 1, what should be done if 'iname' is not needed as the identifier?
