### ISSUE TITLE
awesome tool!

### ISSUE THREAD

**Issue by gzchenjiajun** [darkpgmr/DarkLabel#9]
awesome tool!

**Comment by haviduck** [comment]
sofry for adding to a closed issue but damn yeah. praise where praise is due. ive tried tvem all at this point and this one just gets it. reshaping existing bboxes, good tracking, easy custom output... if i was to request one thing it would be to intrgrate cpu bbackbone support. imagine being able to pseudolabel using darknet and track via this. man you nailed it and has saved me alot of frustration
